// esbuild.config.mjs
import esbuild from "esbuild";
import process from "process";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

esbuild.build({
    banner: {
        js: banner,
    },
    // --- 关键修改 ---
    // 明确告诉 esbuild 入口文件在 src 目录下
    entryPoints: ["src/main.ts"], 
    
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    charset: 'utf8',
}).catch(() => process.exit(1));
