/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AgentKitPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/core/Orchestrator.ts
var import_obsidian = require("obsidian");

// src/core/utils.ts
var _Logger = class {
  static setDebugMode(debug) {
    _Logger.isDebug = debug;
  }
  static log(message, ...args) {
    if (_Logger.isDebug) {
      console.log(`[OAK] ${message}`, ...args);
    }
  }
  static warn(message, ...args) {
    console.warn(`[OAK] ${message}`, ...args);
  }
  static error(message, ...args) {
    console.error(`[OAK] ${message}`, ...args);
  }
};
var Logger = _Logger;
Logger.isDebug = false;

// src/core/Orchestrator.ts
var Orchestrator = class {
  constructor(plugin) {
    this._isRunning = false;
    this.agents = [];
    this.plugin = plugin;
  }
  get isRunning() {
    return this._isRunning;
  }
  registerAgent(agent) {
    this.agents.push(agent);
    if (!this.plugin.queueData[agent.queueName]) {
      this.plugin.queueData[agent.queueName] = [];
    }
    Logger.log(`Registered Agent: ${agent.constructor.name} -> Queue: ${agent.queueName}`);
  }
  async addToQueue(queueName, item) {
    if (!this.plugin.queueData[queueName]) {
      this.plugin.queueData[queueName] = [];
    }
    item.retries = 0;
    if (!item.id)
      item.id = Date.now().toString();
    this.plugin.queueData[queueName].push(item);
    await this.plugin.persistence.saveQueueData(this.plugin.queueData);
    Logger.log(`Task added to ${queueName}`);
  }
  start() {
    if (this._isRunning)
      return;
    this._isRunning = true;
    new import_obsidian.Notice("🚀 OAK 引擎已启动");
    Logger.log("Engine started");
    this.loop().catch((err) => Logger.error("Loop error:", err));
  }
  stop() {
    this._isRunning = false;
    new import_obsidian.Notice("🛑 OAK 引擎已停止");
    Logger.log("Engine stopped");
  }
  async loop() {
    if (!this._isRunning)
      return;
    let workDone = false;
    for (const agent of this.agents) {
      if (!this._isRunning)
        break;
      const queueName = agent.queueName;
      const queue = this.plugin.queueData[queueName];
      if (queue && queue.length > 0) {
        const item = queue[0];
        try {
          Logger.log(`Processing task in ${queueName}...`);
          const success = await agent.process(item);
          if (success) {
            queue.shift();
            workDone = true;
          } else {
            throw new Error("Agent process returned false.");
          }
        } catch (error) {
          Logger.error(`Agent ${agent.constructor.name} failed:`, error);
          workDone = true;
          const failedItem = queue.shift();
          if (failedItem) {
            failedItem.retries = (failedItem.retries || 0) + 1;
            const maxRetries = this.plugin.settings.maxRetries || 3;
            if (failedItem.retries < maxRetries) {
              queue.push(failedItem);
              Logger.warn(`Task retrying (${failedItem.retries}/${maxRetries})`);
            } else {
              Logger.error(`Task max retries reached. Discarding.`);
              new import_obsidian.Notice(`任务已达最大重试次数，已被放弃。`);
            }
          }
        } finally {
          await this.plugin.persistence.saveQueueData(this.plugin.queueData);
        }
      }
    }
    const delay = workDone ? 100 : 2e3;
    if (this._isRunning) {
      setTimeout(() => {
        this.loop().catch((err) => Logger.error("Loop timeout error:", err));
      }, delay);
    }
  }
};

// src/core/LLMProvider.ts
var import_obsidian2 = require("obsidian");
var LLMProvider = class {
  constructor(getSettings) {
    this.getSettings = getSettings;
    // 内存中维护 Key 的状态（重启 Obsidian 后重置）
    this.keyUsageOpenAI = /* @__PURE__ */ new Map();
    this.keyUsageGoogle = /* @__PURE__ */ new Map();
    // 失败冷却时间 (秒)
    this.COOLDOWN_SECONDS = 300;
  }
  /**
   * 对外的主入口：智能调度
   */
  async chat(prompt) {
    const settings = this.getSettings();
    const provider = settings.llmProvider;
    try {
      if (provider === "openai") {
        return await this.tryOpenAIFirst(prompt);
      } else {
        return await this.tryGoogleFirst(prompt);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      Logger.error("[LLM Fatal Error]", error);
      new import_obsidian2.Notice(`AI 全线崩溃: ${msg}`);
      return "";
    }
  }
  // --- 策略层 ---
  async tryOpenAIFirst(prompt) {
    try {
      return await this.callOpenAI(prompt);
    } catch (e) {
      Logger.warn("OpenAI failed, attempting failover to Google...", e);
      if (this.getKeys(this.getSettings().googleApiKey).length > 0) {
        new import_obsidian2.Notice("OpenAI 暂时不可用，正在切换至 Google...");
        return await this.callGoogle(prompt);
      }
      throw e;
    }
  }
  async tryGoogleFirst(prompt) {
    try {
      return await this.callGoogle(prompt);
    } catch (e) {
      Logger.warn("Google failed, attempting failover to OpenAI...", e);
      if (this.getKeys(this.getSettings().openaiApiKey).length > 0) {
        new import_obsidian2.Notice("Google 暂时不可用，正在切换至 OpenAI...");
        return await this.callOpenAI(prompt);
      }
      throw e;
    }
  }
  // --- 执行层 (含多 Key 轮换) ---
  async callOpenAI(prompt) {
    const settings = this.getSettings();
    const keys = this.getAvailableKeys(settings.openaiApiKey, "openai");
    if (keys.length === 0)
      throw new Error("OpenAI API Key 耗尽或未配置 (所有 Key 均在冷却中)");
    let lastError = null;
    for (const apiKey of keys) {
      try {
        Logger.log(`Trying OpenAI Key: ...${apiKey.slice(-4)}`);
        const result = await this._requestOpenAI(apiKey, settings, prompt);
        this.resetCooldown(apiKey, "openai");
        return result;
      } catch (error) {
        Logger.warn(`OpenAI Key ...${apiKey.slice(-4)} failed: ${error.message}`);
        lastError = error;
        if (this.isQuotaError(error)) {
          this.applyCooldown(apiKey, "openai");
        }
      }
    }
    throw lastError || new Error("All OpenAI keys failed.");
  }
  async callGoogle(prompt) {
    const settings = this.getSettings();
    const keys = this.getAvailableKeys(settings.googleApiKey, "google");
    if (keys.length === 0)
      throw new Error("Google API Key 耗尽或未配置");
    let lastError = null;
    for (const apiKey of keys) {
      try {
        Logger.log(`Trying Google Key: ...${apiKey.slice(-4)}`);
        const result = await this._requestGoogle(apiKey, settings, prompt);
        this.resetCooldown(apiKey, "google");
        return result;
      } catch (error) {
        Logger.warn(`Google Key ...${apiKey.slice(-4)} failed: ${error.message}`);
        lastError = error;
        if (this.isQuotaError(error)) {
          this.applyCooldown(apiKey, "google");
        }
      }
    }
    throw lastError || new Error("All Google keys failed.");
  }
  // --- 底层请求 (Base Request) ---
  async _requestOpenAI(apiKey, settings, prompt) {
    const url = `${settings.openaiBaseUrl.replace(/\/$/, "")}/chat/completions`;
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      headers: { "Content-Type": "application/json", "Authorization": `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: settings.openaiModel,
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7
      })
    });
    if (response.status >= 400)
      throw new Error(`OpenAI Status ${response.status}`);
    return response.json.choices[0].message.content.trim();
  }
  async _requestGoogle(apiKey, settings, prompt) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${settings.googleModel}:generateContent?key=${apiKey}`;
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] })
    });
    if (response.status >= 400)
      throw new Error(`Google Status ${response.status}`);
    if (response.json.candidates && response.json.candidates.length > 0) {
      return response.json.candidates[0].content.parts[0].text.trim();
    }
    return "";
  }
  // --- 辅助工具 ---
  getKeys(keyString) {
    if (!keyString)
      return [];
    return keyString.split("\n").map((k) => k.trim()).filter((k) => k.length > 0);
  }
  getAvailableKeys(keyString, provider) {
    const allKeys = this.getKeys(keyString);
    const map = provider === "openai" ? this.keyUsageOpenAI : this.keyUsageGoogle;
    const now = Date.now() / 1e3;
    return allKeys.filter((key) => {
      const usage = map.get(key);
      if (!usage)
        return true;
      return now >= usage.cooldown_until;
    });
  }
  isQuotaError(error) {
    const msg = (error.message || "").toLowerCase();
    if (msg.includes("429") || msg.includes("401") || msg.includes("403"))
      return true;
    if (msg.includes("quota") || msg.includes("rate limit") || msg.includes("insufficient"))
      return true;
    return false;
  }
  applyCooldown(key, provider) {
    const map = provider === "openai" ? this.keyUsageOpenAI : this.keyUsageGoogle;
    map.set(key, { cooldown_until: Date.now() / 1e3 + this.COOLDOWN_SECONDS });
    Logger.warn(`❄️ Key ...${key.slice(-4)} 冷却 5 分钟.`);
  }
  resetCooldown(key, provider) {
    const map = provider === "openai" ? this.keyUsageOpenAI : this.keyUsageGoogle;
    map.delete(key);
  }
};

// src/core/Persistence.ts
var import_obsidian3 = require("obsidian");
var Persistence = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.app = plugin.app;
    this.cacheDir = (0, import_obsidian3.normalizePath)(`${this.app.vault.configDir}/plugins/${this.plugin.manifest.id}/task_cache`);
    this.queueFile = (0, import_obsidian3.normalizePath)(`${this.app.vault.configDir}/plugins/${this.plugin.manifest.id}/queues.json`);
  }
  async init() {
    const adapter = this.app.vault.adapter;
    if (!await adapter.exists(this.cacheDir)) {
      await adapter.mkdir(this.cacheDir);
    }
  }
  // --- 队列数据管理 ---
  async loadQueueData() {
    const adapter = this.app.vault.adapter;
    if (await adapter.exists(this.queueFile)) {
      try {
        const content = await adapter.read(this.queueFile);
        return JSON.parse(content);
      } catch (e) {
        Logger.error("Failed to load queue data:", e);
        return {};
      }
    }
    return {};
  }
  async saveQueueData(queues) {
    const adapter = this.app.vault.adapter;
    try {
      await adapter.write(this.queueFile, JSON.stringify(queues, null, 2));
      Logger.log("Queue data saved.");
    } catch (e) {
      Logger.error("Failed to save queue data:", e);
    }
  }
  // --- 任务内容缓存 (用于 Agent 间传递大数据) ---
  getCachePath(taskId) {
    const safeName = taskId.replace(/[\\/*?:"<>|]/g, "").trim();
    return `${this.cacheDir}/${safeName}.md`;
  }
  async saveTaskCache(taskId, content) {
    const path = this.getCachePath(taskId);
    try {
      await this.app.vault.adapter.write(path, content);
      Logger.log(`Saved task cache: ${taskId}`);
    } catch (e) {
      Logger.error(`Failed to save task cache for ${taskId}:`, e);
    }
  }
  async loadTaskCache(taskId) {
    const path = this.getCachePath(taskId);
    try {
      if (await this.app.vault.adapter.exists(path)) {
        return await this.app.vault.adapter.read(path);
      }
    } catch (e) {
      Logger.error(`Failed to load task cache for ${taskId}:`, e);
    }
    return "";
  }
  async deleteTaskCache(taskId) {
    const path = this.getCachePath(taskId);
    try {
      if (await this.app.vault.adapter.exists(path)) {
        await this.app.vault.adapter.remove(path);
        Logger.log(`Deleted task cache: ${taskId}`);
      }
    } catch (e) {
      Logger.warn(`Failed to delete task cache for ${taskId}:`, e);
    }
  }
};

// src/core/BaseAgent.ts
var BaseAgent = class {
  constructor(plugin, llm) {
    this.plugin = plugin;
    this.llm = llm;
  }
  get settings() {
    return this.plugin.settings;
  }
  get app() {
    return this.plugin.app;
  }
  // 提供便捷的日志方法
  log(msg) {
    Logger.log(`[${this.constructor.name}] ${msg}`);
  }
  error(msg, ...args) {
    Logger.error(`[${this.constructor.name}] ${msg}`, ...args);
  }
};

// src/agents/GeneratorAgent.ts
var _GeneratorAgent = class extends BaseAgent {
  get queueName() {
    return _GeneratorAgent.QUEUE_NAME;
  }
  async process(item) {
    console.debug(`[GeneratorAgent] 正在处理概念: ${item.concept}`);
    const prompt = this.settings.prompt_generator.replace("{concept}", item.concept);
    const content = await this.llm.chat(prompt);
    if (!content || content.trim().length === 0) {
      console.error("[GeneratorAgent] LLM 返回内容为空。");
      return false;
    }
    const outputDir = this.settings.output_dir;
    const fileName = `${item.concept.replace(/[\\/:"*?<>|]/g, "_")}.md`;
    const filePath = `${outputDir}/${fileName}`;
    const fileExists = await this.app.vault.adapter.exists(filePath);
    if (fileExists) {
      console.warn(`[GeneratorAgent] 文件已存在，跳过创建: ${filePath}`);
      return true;
    }
    await this.app.vault.create(filePath, content);
    console.debug(`[GeneratorAgent] 已成功创建文件: ${filePath}`);
    return true;
  }
};
var GeneratorAgent = _GeneratorAgent;
GeneratorAgent.QUEUE_NAME = "generation_queue";

// src/settings.ts
var import_obsidian4 = require("obsidian");
var OAKSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("General").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Debug mode").setDesc("在控制台显示详细日志 (推荐开启以观察故障切换)").addToggle((toggle) => toggle.setValue(this.plugin.settings.debug_mode).onChange(async (value) => {
      this.plugin.settings.debug_mode = value;
      Logger.setDebugMode(value);
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Primary Provider").setDesc("首选 AI 提供商。当其所有 Key 均不可用时，会自动尝试另一个。").addDropdown((d) => d.addOption("openai", "OpenAI").addOption("google", "Google").setValue(this.plugin.settings.llmProvider).onChange(async (v) => {
      this.plugin.settings.llmProvider = v;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.llmProvider === "openai") {
      new import_obsidian4.Setting(containerEl).setName("OpenAI Settings").setHeading();
      this.addOpenAISettings(containerEl);
      this.addGoogleSettings(containerEl);
    } else {
      new import_obsidian4.Setting(containerEl).setName("Google Settings").setHeading();
      this.addGoogleSettings(containerEl);
      this.addOpenAISettings(containerEl);
    }
    new import_obsidian4.Setting(containerEl).setName("Engine Settings").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Output Folder").addText((t) => t.setValue(this.plugin.settings.output_dir).onChange(async (v) => {
      this.plugin.settings.output_dir = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Max Retries").addText((t) => t.setValue(String(this.plugin.settings.maxRetries)).onChange(async (v) => {
      this.plugin.settings.maxRetries = parseInt(v);
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Prompt Template").addTextArea((t) => {
      t.setValue(this.plugin.settings.prompt_generator).onChange(async (v) => {
        this.plugin.settings.prompt_generator = v;
        await this.plugin.saveSettings();
      });
      t.inputEl.rows = 5;
      t.inputEl.style.width = "100%";
    });
  }
  addOpenAISettings(el) {
    new import_obsidian4.Setting(el).setName("OpenAI Keys").setDesc("一行一个 Key。支持自动轮换和冷却。").addTextArea((t) => {
      t.setValue(this.plugin.settings.openaiApiKey).onChange(async (v) => {
        this.plugin.settings.openaiApiKey = v;
        await this.plugin.saveSettings();
      });
      t.inputEl.rows = 3;
      t.inputEl.style.width = "100%";
    });
    new import_obsidian4.Setting(el).setName("Base URL").addText((t) => t.setValue(this.plugin.settings.openaiBaseUrl).onChange(async (v) => {
      this.plugin.settings.openaiBaseUrl = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(el).setName("Model").addText((t) => t.setValue(this.plugin.settings.openaiModel).onChange(async (v) => {
      this.plugin.settings.openaiModel = v;
      await this.plugin.saveSettings();
    }));
  }
  addGoogleSettings(el) {
    new import_obsidian4.Setting(el).setName("Google Keys").setDesc("一行一个 Key。").addTextArea((t) => {
      t.setValue(this.plugin.settings.googleApiKey).onChange(async (v) => {
        this.plugin.settings.googleApiKey = v;
        await this.plugin.saveSettings();
      });
      t.inputEl.rows = 3;
      t.inputEl.style.width = "100%";
    });
    new import_obsidian4.Setting(el).setName("Model").addText((t) => t.setValue(this.plugin.settings.googleModel).onChange(async (v) => {
      this.plugin.settings.googleModel = v;
      await this.plugin.saveSettings();
    }));
  }
};

// src/InputModal.ts
var import_obsidian5 = require("obsidian");
var InputModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "🌱 播种新概念" });
    let inputElement;
    new import_obsidian5.Setting(contentEl).setName("输入概念名称").setDesc("输入你想生成的知识点，例如：'第一性原理'").addText((text) => {
      inputElement = text.inputEl;
      text.onChange((value) => {
        this.result = value;
      });
      text.inputEl.addEventListener("keypress", (e) => {
        if (e.key === "Enter") {
          this.submit();
        }
      });
    });
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText("添加到队列").setCta().onClick(() => {
      this.submit();
    }));
    setTimeout(() => inputElement == null ? void 0 : inputElement.focus(), 0);
  }
  submit() {
    if (this.result && this.result.trim().length > 0) {
      this.close();
      this.onSubmit(this.result.trim());
    } else {
      this.close();
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/core/EventBus.ts
var import_obsidian6 = require("obsidian");
var EventBus = class extends import_obsidian6.Events {
  constructor() {
    super();
  }
  static getInstance() {
    if (!EventBus.instance) {
      EventBus.instance = new EventBus();
    }
    return EventBus.instance;
  }
  // 封装 emit 以便统一记录日志
  emit(eventName, ...args) {
    Logger.log(`[EventBus] Emitting: ${eventName}`, args);
    super.trigger(eventName, ...args);
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  llmProvider: "openai",
  openaiApiKey: "",
  openaiBaseUrl: "https://api.openai.com/v1",
  openaiModel: "gpt-3.5-turbo",
  googleApiKey: "",
  googleModel: "gemini-1.5-flash",
  maxRetries: 3,
  prompt_generator: "请详细解释概念: {concept}，包含定义、原理和应用。",
  output_dir: "KnowledgeGraph",
  debug_mode: false
};
var AgentKitPlugin = class extends import_obsidian7.Plugin {
  // --- 核心：暴露 API 给其他插件 ---
  get api() {
    return {
      version: this.manifest.version,
      registerAgent: (agent) => this.orchestrator.registerAgent(agent),
      // 1. 异步任务调度
      dispatch: async (queueName, payload, sourcePluginId) => {
        const item = { ...payload, sourcePluginId: sourcePluginId || "External" };
        await this.orchestrator.addToQueue(queueName, item);
        if (!this.orchestrator.isRunning)
          this.orchestrator.start();
        return item.id;
      },
      // 2. [新增] 同步/即时对话接口
      // 供 Lite Chat 等插件直接调用，跳过队列
      chat: async (prompt) => {
        return await this.llm.chat(prompt);
      },
      on: (event, cb) => this.eventBus.on(event, cb),
      off: (event, cb) => this.eventBus.off(event, cb)
    };
  }
  // ------------------------------
  async onload() {
    await this.loadSettings();
    Logger.setDebugMode(this.settings.debug_mode);
    this.persistence = new Persistence(this);
    await this.persistence.init();
    this.queueData = await this.persistence.loadQueueData();
    this.eventBus = EventBus.getInstance();
    if (!await this.app.vault.adapter.exists(this.settings.output_dir)) {
      await this.app.vault.createFolder(this.settings.output_dir);
    }
    this.addSettingTab(new OAKSettingTab(this.app, this));
    this.llm = new LLMProvider(() => this.settings);
    this.orchestrator = new Orchestrator(this);
    this.orchestrator.registerAgent(new GeneratorAgent(this, this.llm));
    this.addCommand({
      id: "add-custom-concept",
      name: "添加新概念到生成队列",
      callback: () => {
        new InputModal(this.app, (concept) => {
          this.api.dispatch(GeneratorAgent.QUEUE_NAME, { concept }, "OAK-GUI").then(() => new import_obsidian7.Notice(`已将 '${concept}' 加入队列。`));
        }).open();
      }
    });
    this.addCommand({
      id: "toggle-oak",
      name: "启动/停止 OAK 引擎",
      callback: () => {
        if (this.orchestrator.isRunning) {
          this.orchestrator.stop();
        } else {
          this.orchestrator.start();
        }
      }
    });
    this.addRibbonIcon("bot", "OAK: 添加新概念", () => {
      new InputModal(this.app, (concept) => {
        this.api.dispatch(GeneratorAgent.QUEUE_NAME, { concept }, "OAK-Ribbon");
      }).open();
    });
    Logger.log("OAK Agent Kit (Framework Mode) loaded.");
  }
  onunload() {
    this.orchestrator.stop();
    Logger.log("OAK Agent Kit unloaded.");
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
